from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QVBoxLayout, QRadioButton, QHBoxLayout, QMessageBox
def victory():
    victory_win = QMessageBox()
    victory_win.setText('Верно! Вы выиграли гироскутер')
    victory_win.exec_()
    main_window.close()
def lose():
    lose_loser = QMessageBox()
    lose_loser.setText('Нет, в 2015 году. Вы выиграли фирменный плакат')
    lose_loser.exec_()
    main_window.close()
app = QApplication([])
main_window = QWidget()
main_window.setWindowTitle('Конкурс от Crazy People')
main_window.resize(400, 200)
text = QLabel('В каком году канал получил "золотую кнопку" от YouTube?')
r_btn1 = QRadioButton('2005')
r_btn2 = QRadioButton('2010')
r_btn3 = QRadioButton('2015')
r_btn4 = QRadioButton('2020')
v_line = QVBoxLayout()
h_line1 = QHBoxLayout()
h_line2 = QHBoxLayout()
h_line3 = QHBoxLayout()
h_line1.addWidget(text, alignment= Qt.AlignCenter)
h_line2.addWidget(r_btn1, alignment= Qt.AlignCenter)
h_line2.addWidget(r_btn2, alignment= Qt.AlignCenter)
h_line3.addWidget(r_btn3, alignment= Qt.AlignCenter)
h_line3.addWidget(r_btn4, alignment= Qt.AlignCenter)
v_line.addLayout(h_line1)
v_line.addLayout(h_line2)
v_line.addLayout(h_line3)
r_btn3.clicked.connect(victory)
r_btn1.clicked.connect(lose)
r_btn2.clicked.connect(lose)
r_btn4.clicked.connect(lose)
main_window.setLayout(v_line)
main_window.show()
app.exec()